benchmark:
  - polybench.source:
      -
        POLYBENCH_NAME: "polybench_list.txt"
        POLYBENCH_DATASET: "MINI_DATASET"
      -
        POLYBENCH_NAME: "polybench_list.txt"
        POLYBENCH_DATASET: "SMALL_DATASET"
  - xsbench.source:
      -
        XSBENCH_DATASET: "small"
        XSBENCH_LOOKUP: "1500"
sim_params:
  -
    CACHE_SIZE:
        - "8MB"
        - "16MB"
    CACHELINE: "256"
  -
    CACHE_SIZE: "1MB"
    CACHELINE: "128"
